# Generated by Django 3.1.6 on 2021-03-01 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='text_for_detailed',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
